### ISSUE TITLE
Latest revision which fixes haskell-src-exts issue has not been uploaded to Hackage

### ISSUE THREAD

**Issue by tebello-thejane** [23Skidoo/pointful#6]
The issue with `haskell-src-exts` was fixed in November, but the latest version on Hackage is from March. The latest version needs to uploaded (which a version number bump).

**Comment by 23Skidoo** [comment]
Thanks for the heads-up! Will do.

**Comment by bergmark** [comment]
I published a revision to 1.0.6 disallowing haskell-src-exts 1.17 https://hackage.haskell.org/package/pointful-1.0.6/revisions/

**Comment by 23Skidoo** [comment]
1.0.7 released on Hackage.

@bergmark Nice, thanks.
