### ISSUE TITLE
 Using pointful on line returns incorrect haskell

### ISSUE THREAD

**Issue by ivanperez-keera** [23Skidoo/pointful#9]
Hi

This issue was discovered while using pointful and haskell-vim-now. See: https://github.com/begriffs/haskell-vim-now/issues/108

I just added the following to a haskell file:
``` haskell
h x = f (filter ('a' ==) x)
```
When I use `,h.` (transform into point-free style) it is correctly converted to:
``` haskell
h = f . filter ('a' ==)
```
When I use  `,h>` (transform into pointed style) it becomes:
```haskell
h d = f (filter (\ a -> 'a' == a) d);
```
with an additional ; at the end, making it invalid haskell. From this point on, pointfree can no longer parse the line.

Is this a bug in pointful?

**Comment by 23Skidoo** [comment]
Yeah, it looks like a semicolon is added for some reason:
```
@unpl h x = f (filter ('a' ==) x)
h x = f (filter (\ a -> 'a' == a) x);
@unpl f (filter ('a' ==) x)
f (filter (\ a -> 'a' == a) x)
```

I suggest [moving the issue to the upstream bug tracker](https://github.com/lambdabot/lambdabot/issues/new).

**Comment by 23Skidoo** [comment]
Closing in favour of https://github.com/lambdabot/lambdabot/issues/144.

**Comment by 23Skidoo** [comment]
Upstream closed this as a wontfix.

**Comment by 23Skidoo** [comment]
Opened a ticket at the `haskell-src-exts` bug tracker: https://github.com/haskell-suite/haskell-src-exts/issues/309.
